### ISSUE TITLE
FeedType 객체는 하나의 입력만 들어오도록 처리 필요함.

### ISSUE THREAD

**Issue by hschoi0305** [EXPNUNI/enuSpaceTensorflow#13]
FeedType 객체는 하나의 입력, 하나의 초기 변수만 들어오도록 처리 필요함.

**Comment by BrightJoy** [comment]
여러입력을 하더라도 마지막이 업데이트 되도록 로직이 되어 있음.

**Comment by BrightJoy** [comment]
여러입력을 하더라도 마지막이 업데이트 되도록 로직이 되어 있음.
