### ISSUE TITLE
result의 shape의 value 갯수가 같을 때 shape를 업데이트 하지 않는 현상

### ISSUE THREAD

**Issue by lwh4525** [EXPNUNI/enuSpaceTensorflow#14]
이전에 실행한 결과의 value갯수와 현재 실행한 value갯수가 같을 때 (arraysize가 같을 때) 결과값의 shape를 업데이트 하지 않아서 shape가 계속 동일하게 나옴

**Comment by BrightJoy** [comment]
enuSpace에서 배열정보 체크후 다이얼로그 닫기 기능 추가.
